"""Build expected Pi metadata for startup checks of the published CLI consumer."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import PurePosixPath
from typing import Any

from tetrabench.capabilities import MetadataError, parse_metadata
from tetrabench.harness_config import ResolvedHarness
from tetrabench.reasoning import validate_snapshot_for_harness
from tetrabench.resources import validate_resource_name
from tetrabench.runtime_startup import (
    validate_runtime_capability as validate_runtime_capability,
)


def runtime_capability_probe(
    harness: ResolvedHarness,
    *,
    resource_root: str,
    native_files: Mapping[str, str],
    absent_native_files: tuple[str, ...] = (),
) -> dict[str, Any]:
    """Return expected metadata for the published Pi RPC startup verifier.

    native_files maps actual sandbox settings/models file paths to their expected
    SHA-256, computed by the owner from the generated bytes it uploads. All sealed
    resources are added independently. No credentials or environment values are
    read. Eligible selected catalog metadata retains its native cache validators.
    Startup seeds only an absent private native store, then checks RPC get_state.
    It never replaces an existing/refreshed catalog or claims dispatch enforcement.
    """
    reference = harness.capability_snapshot
    if reference is None:
        raise MetadataError("runtime reasoning probe requires a bound snapshot")
    snapshot = validate_snapshot_for_harness(reference, harness)
    if harness.name != "pi" or harness.version != "0.85.1":
        raise MetadataError("runtime reasoning guard requires Pi 0.85.1")
    metadata = parse_metadata(snapshot.metadata_json)
    if "native" in metadata:
        metadata = metadata["native"]
    capture = metadata.get("runtime_capture")
    if not isinstance(capture, dict):
        raise MetadataError("reinspect with the installed Pi SDK for runtime evidence")
    model = capture.get("model", {})
    required = {
        "id",
        "provider",
        "api",
        "baseUrl",
        "reasoning",
        "maxTokens",
        "contextWindow",
        "input",
        "cost",
        "hasModelHeaders",
    }
    if not required <= model.keys():
        raise MetadataError(
            "native model capture is incomplete; no portable model proof"
        )
    if model["hasModelHeaders"] or model.get("hasOpaqueMetadata", True):
        raise MetadataError("model-header routing needs a native resolved-route guard")
    for limit in ("maxTokens", "contextWindow"):
        if type(model[limit]) is not int or model[limit] <= 0:
            raise MetadataError("native model token limits are incomplete")
    cost = model["cost"]
    if not isinstance(cost, dict) or any(
        type(cost.get(key)) not in {int, float} or cost[key] < 0
        for key in ("input", "output", "cacheRead", "cacheWrite")
    ):
        raise MetadataError("native model pricing is incomplete")
    if not native_files and not absent_native_files:
        raise MetadataError("bind the actual generated native configuration files")
    root = PurePosixPath(resource_root)
    if not root.is_absolute() or ".." in root.parts:
        raise MetadataError("runtime resource root must be an absolute sandbox path")
    bindings = dict(native_files)
    for path in absent_native_files:
        target = PurePosixPath(path)
        validate_resource_name(target.name)
        if not target.is_absolute() or ".." in target.parts or path in bindings:
            raise MetadataError("invalid absent native configuration binding")
    for resource in harness.resources:
        path = str(root / resource.destination)
        if path in bindings and bindings[path] != resource.sha256:
            raise MetadataError("resource and native config file bindings disagree")
        bindings[path] = resource.sha256
    if set(absent_native_files) & bindings.keys():
        raise MetadataError("native absence conflicts with a sealed resource")
    for path, digest in bindings.items():
        target = PurePosixPath(path)
        validate_resource_name(target.name)
        if (
            not target.is_absolute()
            or ".." in target.parts
            or len(digest) != 64
            or any(character not in "0123456789abcdef" for character in digest)
        ):
            raise MetadataError(
                "runtime file binding must have an absolute path and SHA-256"
            )
    return {
        "schema_version": 1,
        "snapshot_sha256": snapshot.digest,
        "identity": snapshot.identity.model_dump(mode="json"),
        "capture": capture,
        "thinking": harness.options.get("thinking"),
        "catalog_entry": metadata.get("native_catalog_entry"),
        "absent_files": list(absent_native_files),
        "files": [
            {"path": path, "sha256": digest}
            for path, digest in sorted(bindings.items())
        ],
    }
